### PR TITLE
Port to Gatsby

### PR DESCRIPTION
**Pull request by Codesleuth**
This change moves the website over from using Hugo to Gatsby.

### 🤔 Why Gatsby?

The Hugo website was basically a stepping stone from the original static HTML version to having a build step that can read content from markdown files. This was incredibly valuable, and has paved the way for being able to use the same markdown files in this Gatsby build.

Using Gatsby we gain two key things:
1. static HTML for browsers with JavaScript disabled
2. enhancement to rich JavaScript UIs if available

There's far more benefits to using Gatsby, but right now these alone are enough of a reason to change.

### 🏠 Hosting

I've set up Travis to automatically build and deploy this branch on my fork. The settings are easy and quick to set up, and to make the process smoother I'll open a PR that ports the Hugo build to do the same thing - then it's just a YAML file overwrite to see this build take place immediately.

If we decide we want to use Netlify at a later date, this process will be easy to migrate.

### 🎨 Design

Yes, it looks the same. I did this on purpose. I didn't want to make any design decisions at the same time as porting the code. It's too easy to get bogged down in design decisions, and it muddles the purpose of this PR if there were both design and build changes at once.

The (much needed) design changes can come afterwards, when it's easier to receive community feedback ✌️ 

### 🐛 Known Issues

Some of the markdown files include images. The default markdown plugin doesn't expose any information about these images, and so they aren't copied to the output. Some also have special class names which are ignored by the parser. This can be fixed by adding another layer to the markdown parsing step, but I thought I would approach this fix separately.

resolves #7

### CODE REVIEW

**Comment by carolgilabert** [comment]
Looks really good! Thanks for doing this 💯 

🔧 The code of conduct page is not working in the branch, though.

**Comment by Codesleuth** [comment]
> 🔧 The code of conduct page is not working in the branch, though.

It's deployed here: https://www.codesleuth.co.uk/nottsjs-website/codeofconduct.html

Might be a base-url issue, I need to try it locally.

**Comment by Codesleuth** [comment]
> > 🔧 The code of conduct page is not working in the branch, though.
> 
> It's deployed here: https://www.codesleuth.co.uk/nottsjs-website/codeofconduct.html
> 
> Might be a base-url issue, I need to try it locally.

Looks like there was an issue, you're right. I've fixed it

**Review by carolgilabert — APPROVED** [review]
LGTM! After the conflicts are fixed 😅

tenor

**Pull request merged**
